### ISSUE TITLE
Add new resources

### ISSUE THREAD

**Issue by FabianCristancho** [cosmoart/free-resources#1]
Hi! I'd like to add new interesting resources about patterns, fonts and icons. Please give the chance 😄

**Comment by cosmoart** [comment]
Of course, the website is still in development and may change some things, but you can contribute new resources, see [CONTRIBUTING.md](https://github.com/cosmoart/free-resources/blob/main/CONTRIBUTING.md) to see how to do it, if you have any questions I will be happy to answer them 😁.
